### PR TITLE
feature(styleguide): Start moving to typescript

### PR DESCRIPTION
**Pull request by lpirola**

### CODE REVIEW

**Comment by lpirola** [comment]
Componentes restantes para completar migração dos prop-types para interface do typescript:

- [ ] ./src/components/await/Loading/atoms/Sparkles.tsx
- [ ] ./src/components/progress/ProgressBar/ProgressBar.tsx
- [ ] ./src/components/cards/Tooltip/Tooltip.tsx
- [ ] ./src/components/cards/RankingCard/RankingCard.tsx
- [ ] ./src/components/cards/Panel/Panel.tsx
- [ ] ./src/components/cards/AreaChartCard/AreaChartCard.tsx
- [ ] ./src/components/cards/ClickableCard/ClickableCard.tsx
- [ ] ./src/components/cards/FeedsCard/FeedsCard.tsx
- [ ] ./src/components/cards/DataListCard/DataListCard.tsx
- [ ] ./src/components/cards/NumberCard/NumberCard.tsx
- [ ] ./src/components/form/Tag/Tag.tsx
- [ ] ./src/components/form/InputAdornment/InputAdornment.tsx
- [ ] ./src/components/form/InputHint/InputHint.tsx
- [ ] ./src/components/navigation/Navbar/Navbar.tsx
- [ ] ./src/components/navigation/TabItem/TabItem.tsx
- [ ] ./src/components/layout/Scrollbox/Scrollbox.tsx
- [ ] ./src/components/layout/Position/Position.tsx
- [ ] ./src/components/layout/Modal/Modal.tsx
- [ ] ./src/components/layout/Flexbox/Flexbox.tsx
- [ ] ./src/components/layout/Footer/Footer.tsx
- [ ] ./src/components/layout/Flexbox2/Flexbox2.tsx
- [ ] ./src/components/layout/Cell/Cell.tsx
- [ ] ./src/components/layout/Page/Page.tsx
- [ ] ./src/components/layout/Backdrop/Backdrop.tsx
- [ ] ./src/components/list/Feed/Feed.tsx
- [ ] ./src/components/list/DataList/DataList.tsx
- [ ] ./src/components/list/Table/Table.tsx
- [ ] ./src/components/list/DataListCol/DataListCol.tsx
- [ ] ./src/components/list/FeedItem/FeedItem.tsx
- [ ] ./src/components/content/SwitchSlider/SwitchSlider.tsx
- [ ] ./src/components/content/Number/Number.tsx
- [ ] ./src/components/content/Icon/Icon.tsx
- [ ] ./src/components/content/Image/Image.tsx
- [ ] ./src/components/content/Button/Button.tsx
- [ ] ./src/components/content/IconColorful/IconColorful.tsx
- [ ] ./src/components/content/Text/Text.tsx

**Comment by lpirola** [comment]
Tarefas pendentes:

- [ ] pass tests
- [ ] styleguidist serve work again

**Comment by igr-santos** [comment]
@lpirola rodando localmente estou tendo o seguinte problema:

```
../bonde-styleguide/dist/bonde-styleguide.cjs.development.js
Module not found: Can't resolve './assets/bg@2x.png' in '/home/igr/Repos/nossas/bonde-client/packages/bonde-styleguide/dist'
```

Isso acontece no `admin-canary` quando eu executo o comando:

```
yarn lerna run dev --parallel --scope=bonde-admin-canary --scope=bonde-styleguide
```

**Comment by lpirola** [comment]
@igr-santos falta copiar os arquivos png para a pasta de build

**Pull request closed without merging**
