### PR TITLE
Feature community settings in sidebar

### PR DESCRIPTION
**Pull request by gabrielrtakeda**
# Related issues
- Move some community configurations to sidebar when mobilization is not selected #489

### CODE REVIEW

**Review by igr-santos — CHANGES_REQUESTED** [review]
@gabrielrtakeda remove 'configurações' menu in sidebar not was a good idea, when i am editing mobilization, i can't go to configurations of community, because isn't showing the itens of configurations menu nor configuration link

**Comment by gabrielrtakeda** [comment]
@igr-santos I should keep the sidebar without the **configurações** link or it must be back?

**Comment by igr-santos** [comment]
@gabrielrtakeda keep link for configurations of community in sidebar top.

**Comment by gabrielrtakeda** [comment]
@igr-santos Ok, I will do that in the next commits.

**Pull request merged**
