### PR TITLE
Release v0.5.6

### LINKED ISSUE #613: Add message after check if domain is propagated

### PR DESCRIPTION
**Pull request by gabrielrtakeda**
# Related issues
- Add message after check if domain is propagated #613
- Add more info about dimensions from facebook best practices #619
- Improvements when user choose howto publish mobilization #629
- Better handle unauthenticated API request #630
- Add option to use bonde.org domain as default domain #631
- Improve how we set new domain at community page close #613 #632
- Change domain behavior after selectd one at communiy config #633
- Add async count load from pressure and form_entries widget #637
- Bad user expierence whn community have a lot of domains #638
- Community default e-mail was not saved after changes #639

# Related pull-requests
Acceptance tests, each PR with their respective test cases
- [x] Hotfix 401 unauthenticated API request on fetch community #642
- [x] Refactor dns manangement page #643
- [x] Feature improve mobilization domain options #644
- [x] Improve domain experience #646
- [x] Feature add react countup to widgets count #647
- [x] Change field name for custom default email #648
- [x] Feature improve ux community dns section #649
- [x] Add translate for domain notification #650
- [x] Feature add sharing image fb specification #651
- Fix volume path to fit dockerfile config #655
- [x] Feature mobilization slug edit #656

### CODE REVIEW

**Comment by gabrielrtakeda** [comment]
- [x] Community domain page's **domains section** table header name is not shown the full name
http://app.staging.bonde.org/community/domain

screen shot 2017-06-06 at 18 36 55

**Comment by gabrielrtakeda** [comment]
- [x] Community domains page's **DNS records section** new record **value** input is too big
http://app.staging.bonde.org/community/domain

screen shot 2017-06-06 at 18 41 11

**Comment by gabrielrtakeda** [comment]
- [x] Community domains page's **DNS record section** remove record modal content overflow
http://app.staging.bonde.org/community/domain

screen shot 2017-06-06 at 18 57 56

**Comment by gabrielrtakeda** [comment]
[This](https://github.com/nossas/bonde-client/pull/652#issuecomment-306626029) is a textarea. I increase a bit more the textarea rows quantity to make it explicit that is a textarea.

**Comment by lpirola** [comment]
- [x] Improve shadow from dialog notifications

| **prev**                                                                                                                                                             | **now**                                                                                                                                                              |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| screen shot 2017-06-07 at 15 46 44 | screen shot 2017-06-07 at 15 46 57 |

- [x] Improve border color when domains is activated, to a design that looks more like reapop notifications dialog

| **prev**                                                                                                                                                              | **now**                                                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| screen shot 2017-06-07 at 15 55 55 | screen shot 2017-06-07 at 15 56 10 |

- [x] Copy styles from reapop notification dialog to warning at recipient page in community config

| **prev**                                                                                                                                                              | **now**                                                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| screen shot 2017-06-07 at 15 57 21 | screen shot 2017-06-07 at 15 57 33 |

- [x] Remove title from domain page at community settings

| **prev**                                                                                                                                                              | **now**                                                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| screen shot 2017-06-07 at 15 58 26 | screen shot 2017-06-07 at 15 58 35 |

- [x] Remove title from add domain page at community settings

| **prev**                                                                                                                                                              | **now**                                                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| screen shot 2017-06-07 at 15 59 29 | screen shot 2017-06-07 at 15 59 42 |

**Pull request merged**
