### PR TITLE
Refactor modules

### PR DESCRIPTION
**Pull request by lpirola**

### CODE REVIEW

**Comment by gabrielrtakeda** [comment]
## Still needs one more little migration
It still needs to migrate **app/modules/widgets** module into **app/modules/mobilizations** to make it a sibling module of **blocks** module.

**Comment by gabrielrtakeda** [comment]
## Old mobilization module files migration
One more thing that must be is migrate all **app/scripts/Mobilization** module files to **app/modules/mobilizations** module.

This may be solved in next few commits.

**Comment by gabrielrtakeda** [comment]
## Mobilization public view error
It seems like `custom-domain-page` do not rendering things rightly.

### Screenshot
screen shot 2017-01-11 at 09 13 42

I really do not know what is wrong. Needs to be fixed.

---

✅ Tested and approved: b3f0611865f49d828802469c521cbaeb2bb2ff99

**Comment by gabrielrtakeda** [comment]
## Empty widgets after create new block
It needs to understand why widgets list are empty after creating a new block

### Screenshot
screen shot 2017-01-11 at 10 28 53

The block with **darkgray** background has been just created, and the widgets does not appear. If returns to mobilizations list page and click to edit the mobilization again, the **draft widgets** appears correctly.

It may related to state manipulation when block has created or something about..
Needs to fix.

---

✅ Tested and approved: e24fd9ed7b2dda00cfff0c31d0b297a1d387dd2e

**Comment by gabrielrtakeda** [comment]
# Staging Smoke-Test Feedback I

## Form widget settings page does not accessible
When try to access form widget settings page the error and warnings bellow was dispatched:

```
Warning: Failed propType: Required prop `mobilization` was not specified in `SettingsContainer`. Check the render method of `Connect(SettingsContainer)`.
Warning: Failed propType: Required prop `mobilization` was not specified in `SettingsFieldsPage`. Check the render method of `Connect(SettingsFieldsPage)`.
Warning: Failed propType: Required prop `mobilization` was not specified in `SettingsMenu`. Check the render method of `SettingsFieldsPage`.
Warning: Failed propType: Required prop `mobilization` was not specified in `Form`. Check the render method of `SettingsFieldsPage`.
Uncaught TypeError: Cannot read property 'id' of undefined
    at new SettingsMenu (settings-menu.js:8)
```

---

✅ Tested and approved: a19837fc0b36bd85b0ae4ddb7f05a288bebfbd95

**Comment by gabrielrtakeda** [comment]
## Error in form widget settings data export page
When have try to access data export settings page of form widget, the following error was dispatched:

```
Uncaught TypeError: Cannot read property 'data' of undefined
    at DataExportPage.render (data-export-page.js:146)
```

Same for **autofire-form-page**.
Needs to fix.

---

✅ Tested and approved: 6ca1d2273b470cbcf10986ecbee71631a011cece

**Comment by gabrielrtakeda** [comment]
## Widgets settings page tab links routes confusion
When access form widget settings page for example, the first route that access is correct but, if looks wight in gif below, do not make any tab as **active** and, when click in another tab, the mobilization id in url changes to another that is not the current mobilization settings page.

jan-12-2017 09-04-08

Needs to fix.

---

✅ Tested and approved: a82bbe685040ee6dc913104de9ae90f35e660826

**Comment by gabrielrtakeda** [comment]
## Not found mobilization templates list page route
When have try to access mobilization templates list page, it cannot find the route and shows 404 error page.

**Screenshot**
screen shot 2017-01-12 at 10 40 06

Needs to fix.

**Comment by lpirola** [comment]
I have found two bugs:

* Configuration page from communities are not loading.
* Profile page show behind sidebar

**Pull request merged**
