### PR TITLE
Feature activists module

### LINKED ISSUE #591: Make a selectable list
[ ] Should possible mark item on list (onCheck)
[ ] Should possible select item on list (onSelect)

### LINKED ISSUE #592: Make an input filter by period date
Could be:

```
// FORMAT PERIOD DATE (DD/MM/YYYY - DD/MM/YYYY)

PeriodFilter.propTypes = {
  onChange: PropTypes.func,
  value: PropType.string
}
```

### LINKED ISSUE #593: Make an input filter by suggestions
Could be:

```
// Suggestions format array [{ suggestionGroup: [ suggestion1, suggestion2 ] }]

SuggestionsFilter.propTypes = {
  onChange: PropTypes.func,
  value: PropTypes.any,
  suggestions: PropTypes.array
}
```

### LINKED ISSUE #594: Add a page to list activits
- [x] GraphQL fetch
- [x] Pagination

### LINKED ISSUE #596: Add a preview for profile selected in activist list

### LINKED ISSUE #793: Add view for related tags in detail activists on activists management

### LINKED ISSUE #815: Finish an activists module usable

### PR DESCRIPTION
**Pull request by igr-santos**
# Issues

- Add a page to list activits. [Closes #594]
- Make a selectable list. [Closes #591]
- Add a preview for profile selected in activist list. [Closes #596]
- Make an input filter by suggestions. [Closes #593]
- Finish an activists module usable [Closes #815]
- Make an input filter by suggestions [Closes #593]
- Add view for related tags in detail activists on activists management [Closes #793]
- Make an input filter by period date [Closes #592]

# Blocked by

- https://github.com/nossas/bonde-server/pull/341
- https://github.com/nossas/bonde-server/pull/370
- https://github.com/nossas/bonde-server/pull/352

# How to test

1. Log in Bonde
2. Open `/activists` url

### CODE REVIEW

**Comment by lpirola** [comment]
@igr-santos pode dar rebase para subir em staging?

**Comment by igr-santos** [comment]
Rebase

**Comment by lpirola** [comment]
@igr-santos continua com conflito :S

**Comment by lpirola** [comment]
Depois de rodar esse job no CI https://ci.bonde.org/nossas/bonde-client/71 a url /activists dava como não encontrado.

**Comment by igr-santos** [comment]
@lpirola na minha perspectiva falta apenas ajustar o layout e a funcionalidade estará completa, se possível fazer os testes e informar nesta thread o feedback

**Review by lpirola — APPROVED** [review]

**Pull request merged**
