### PR TITLE
Mobilization edit-viewer module. part I

### PR DESCRIPTION
**Pull request by igr-santos**

### CODE REVIEW

**Comment by gabrielrtakeda** [comment]
@igr-santos Do you did the rebase of branch develop into your branch? I ran the tests locally and the following error was dispatched:

```
 FAIL  test/client/unit/mobilizations/widgets/__plugins__/match/components/__match__.spec.js
  ● Test suite failed to run

    Cannot find module 'react-mixin' from 'tab.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (client/components/navigation/tabs/tab.js:3:45)
      at Object.<anonymous> (client/components/navigation/tabs/index.js:1:1028)
```

But, the `react-mixin` package was removed in the previous merge..

Can you rebase your branch with branch develop, please.

**Comment by gabrielrtakeda** [comment]
@igr-santos I have make some code review and, I think the refactor was great! All components that have to access the state, are accessing it directly using `connect()`, the "config" to access the state are separated into an another file called `[name].connected.js`, the **selectors** files are a function that receives **state** and **props** returning an object with _selector functions_ available to use, the modules are well documented, I really liked the idea of a config file for setting up the widget plugins and actions/components are heavily tested.

Anyway, I really liked the refactoring. Unfortunately I cannot be able to give a lot of opinion on refactoring but, everything that I saw I really liked. The next step now is to "link" the new refactored components and be happy!

**Comment by gabrielrtakeda** [comment]
@igr-santos Only rebasing your branch will fix the tests in CI.

**The steps to rebase:**
- `git fetch --all`
- `git checkout develop`
- `git pull upstream develop` (upstream: **nossas/bonde-client**)
- `git checkout mobilization-viewer`
- `git rebase develop` (resolve conflicts)
- `git push origin mobilization-viewer -f` (origin: **your-repo/bonde-client**)

**Comment by gabrielrtakeda** [comment]
@igr-santos After rebase, please notify me here (:

**Comment by igr-santos** [comment]
@gabrielrtakeda is done.

**Comment by gabrielrtakeda** [comment]
Thanks @igr-santos! Let's wait CI run the tests to see if it's pass (:

**Comment by gabrielrtakeda** [comment]
Awesome!

```
Test Suites: 4 skipped, 193 passed, 193 of 197 total
Tests:       13 skipped, 769 passed, 782 total
Snapshots:   0 total
Time:        119.479s
Ran all test suites.
Done in 120.46s.
```

**Pull request merged**
