### PR TITLE
Add mobilization viewer

### LINKED ISSUE #356: Refactor and Reorganize reducers from Mobilization, Block and Widget

### LINKED ISSUE #357: Refactor and Reorganize reducers from Widget Donation

### LINKED ISSUE #358: Refactor and Reorganize reducers from Widget Form

### LINKED ISSUE #359: Refactor and Reorganize reducers from Widget Pressure

### LINKED ISSUE #360: Refactor and Reorganize reducers from Widget Content

### LINKED ISSUE #408: Edit mobilization page rendering when change from one to another
# Description
When I try to edit another mobilization after choose a mobilization to edit, the second mobilization that I choosed to edit, does not render. Instead, it renders again the first one that I accessed before.

# Steps to reproduce
1. Access mobilization list page
2. Choose one mobilization to edit
3. Return to the mobilization list page
4. Choose a different mobilization of first one

🐛🐛🐛🐛🐛🐛

### PR DESCRIPTION
**Pull request by igr-santos**
Make routes start to use of mobilization render module

**Fixed issues:**
Closes #408
Closes #360
Closes #359 
Closes #358 
Closes #357 
Closes #356

### CODE REVIEW

**Review by lpirola — APPROVED** [review]

**Review by gabrielrtakeda — CHANGES_REQUESTED** [review]
When I click on a mobilization to edit, the error below was dispatched and do not rendering the page.

**Error:**
```

TypeError: Cannot read property ‘header_font’ of undefined at Pressure.render (webpack:///./client/mobilizations/widgets/__plugins__/pressure/components/__pressure__.js?:138:36)
```

**Comment by gabrielrtakeda** [comment]
I am in doubt if the behaviour to handle the **mouseover** through the application state is a good idea... All the cursor moves on widgets dispatches actions like:

screen shot 2017-03-02 at 11 49 28

**Comment by gabrielrtakeda** [comment]
@igr-santos before we merge these refactoring into branch develop, I think it is better to "link" **all refactored mobilizations** components to each of its respective outdated usages like components, selectors and reducers. In addition to rendering the **mobilizations list page** and **mobilization edit page**, may be it is better to have the other "features" listed below, because it is also part of the mobilization use flow:
- widgets settings page
- enable the behaviour to show the content widget editor's toolbar on click
- enable the behaviour to show the overlay on widgets mouseover

**Comment by igr-santos** [comment]
@gabrielrtakeda I understood your idea, I'll test and refactor these features

**Comment by lpirola** [comment]
I will close all issues referenced in description, they must be in commit message.

**Pull request merged**
