### PR TITLE
Add tab and page to download community report

### LINKED ISSUE #337: Create tab to reports in Community
Zendesk ticket: 128

### PR DESCRIPTION
**Pull request by gabrielrtakeda**
Closes #337, #338

### CODE REVIEW

**Comment by gabrielrtakeda** [comment]
I will unify in this PR also the issue #338 because both are related and dependent each other.

**Comment by gabrielrtakeda** [comment]
I have consumed the nossas/bonde-server#140 and nossas/bonde-server#162 endpoints to achieve the goal of this feature.

**Comment by gabrielrtakeda** [comment]
In endpoint of nossas/bonde-server#162 endpoints, needs to check if the error in screenshot below is an issue related to the implementation code or, something related to my environment.

screen shot 2017-03-03 at 04 33 48

The data of screenshot above follows as below:

**Endpoint:**
- `http://api.reboo.local:3000/communities/1/activist_actions.csv`

**Headers:**
```
Content-Type:application/json
access-token:(_________)
token-type:(_________)
client:(_________)
expiry:(_________)
uid:(_________)
```

**Comment by gabrielrtakeda** [comment]
The goal of this PR have been achieved. Needs to code review and, if it is alright, can made be merged.

**Comment by lpirola** [comment]
@gabrielrtakeda could you resolve the bug found in api?

**Comment by gabrielrtakeda** [comment]
@lpirola Unfortunately not. I only left working the request to the API, if the endpoints `/communities/ID/agg_activists` and `/communities/ID/activist_actions` responds in CSV format like `/communities/${id}/donation_reports.csv`, the frontend will be behave properly.

**Comment by gabrielrtakeda** [comment]
But it still needs to validates with backend guys if it really is a "bug" or that was just an environment issue.

**Comment by devton** [comment]
@gabrielrtakeda this bug is fixed on https://github.com/nossas/bonde-server/pull/194 :)

**Comment by gabrielrtakeda** [comment]
@devton Thanks for the feedback. I'll try the integration with the frontend again and notice you if have some problem.

**Comment by gabrielrtakeda** [comment]
@devton It seems that the endpoint **[GET] /communities/ID/agg_activists** does not exists anymore.. It was replaced for another endpoint or it was removed for now?

**Comment by gabrielrtakeda** [comment]
And the endpoint **[GET] /communities/ID/activist_actions** now works beautifully

**Comment by gabrielrtakeda** [comment]
@devton Which routes is for ** agg_activists**?

```
rake routes | grep communities
community_dns_hosted_zone_dns_records GET      /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records(.:format)     dns_records#index
                                      POST     /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records(.:format)     dns_records#create
 community_dns_hosted_zone_dns_record GET      /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records/:id(.:format) dns_records#show
                                      PATCH    /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records/:id(.:format) dns_records#update
                                      PUT      /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records/:id(.:format) dns_records#update
                                      DELETE   /communities/:community_id/dns_hosted_zones/:dns_hosted_zone_id/dns_records/:id(.:format) dns_records#destroy
           community_dns_hosted_zones GET      /communities/:community_id/dns_hosted_zones(.:format)                                     dns_hosted_zones#index
                                      POST     /communities/:community_id/dns_hosted_zones(.:format)                                     dns_hosted_zones#create
            community_dns_hosted_zone GET      /communities/:community_id/dns_hosted_zones/:id(.:format)                                 dns_hosted_zones#show
                                      PATCH    /communities/:community_id/dns_hosted_zones/:id(.:format)                                 dns_hosted_zones#update
                                      PUT      /communities/:community_id/dns_hosted_zones/:id(.:format)                                 dns_hosted_zones#update
                                      DELETE   /communities/:community_id/dns_hosted_zones/:id(.:format)                                 dns_hosted_zones#destroy
           community_activist_actions GET      /communities/:community_id/activist_actions(.:format)                                     communities/activist_actions#index
            community_payable_details GET      /communities/:community_id/payable_details(.:format)                                      communities/payable_details#index
           community_donation_reports GET      /communities/:community_id/donation_reports(.:format)                                     communities/donation_reports#index
            community_community_users GET      /communities/:community_id/users(.:format)                                                community_users#index
                                      POST     /communities/:community_id/users(.:format)                                                community_users#create
             community_community_user PATCH    /communities/:community_id/users/:id(.:format)                                            community_users#update
                                      PUT      /communities/:community_id/users/:id(.:format)                                            community_users#update
              community_mobilizations GET      /communities/:community_id/mobilizations(.:format)                                        communities#list_mobilizations
                  community_activists GET      /communities/:community_id/activists(.:format)                                            communities#list_activists
                                      POST     /communities/:community_id/activists(.:format)                                            activists#add_activists
                          communities GET      /communities(.:format)                                                                    communities#index
                                      POST     /communities(.:format)                                                                    communities#create
                            community GET      /communities/:id(.:format)                                                                communities#show
                                      PATCH    /communities/:id(.:format)                                                                communities#update
                                      PUT      /communities/:id(.:format)                                                                communities#update
```

**Comment by gabrielrtakeda** [comment]
In conversation with @devton, the goal of endpoint **[GET] /communities/ID/agg_activists** can achieved with the endpoint **[GET] /communities/ID/activists**

It will be fixed into frontend in the next few commits.

**Comment by gabrielrtakeda** [comment]
Now this can be tested and it's ready to merge into branch develop. @igr-santos and @lpirola can you test in staging and approve it, please?

**Comment by igr-santos** [comment]
@gabrielrtakeda Clicked on button to download "RELATÓRIO DE AÇÕES DOS ATIVISTAS" and not work, i receive the following error:

**client-side**
```
GET http://localhost:3000/communities/16/activist_actions.csv 
dispatchXhrRequest @ xhr.js:175
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
report#:1 XMLHttpRequest cannot load http://localhost:3000/communities/16/activist_actions.csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1337' is therefore not allowed access. The response had HTTP status code 500.
createError.js:15 Uncaught (in promise) Error: Network Error
    at createError (createError.js:15)
    at XMLHttpRequest.handleError (xhr.js:87)
```

**server-side**
```
I, [2017-03-15T14:41:45.293765 #4249]  INFO -- : Completed 500 Internal Server Error in 38ms (ActiveRecord: 2.1ms)
D, [2017-03-15T14:41:45.294284 #4249] DEBUG -- sentry: ** [Raven] undefined method `copy_to_string' for #<ActiveRecord::AssociationRelation []> excluded from capture: No server specified, No host specified, No path specified, No public_key specified, No secret_key specified, No project_id specified
F, [2017-03-15T14:41:45.298111 #4249] FATAL -- : 
NoMethodError (undefined method `copy_to_string' for #<ActiveRecord::AssociationRelation []>):
  app/controllers/communities/activist_actions_controller.rb:15:in `block (2 levels) in index'
  app/controllers/communities/activist_actions_controller.rb:10:in `index'


I, [2017-03-15T14:41:45.476841 #4249]  INFO -- :   Rendered /home/igr/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (7.3ms)
I, [2017-03-15T14:41:45.494185 #4249]  INFO -- :   Rendered /home/igr/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (10.4ms)
I, [2017-03-15T14:41:45.503195 #4249]  INFO -- :   Rendered /home/igr/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.3ms)
I, [2017-03-15T14:41:45.504456 #4249]  INFO -- :   Rendered /home/igr/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (40.0ms)
```

The others options to download it's working.

**Review by igr-santos — CHANGES_REQUESTED** [review]
A button download not work.

**Comment by gabrielrtakeda** [comment]
@igr-santos When you pulled your `bonde-server` repository branch **master**, do you runned `rake db:migrate`? The new version of master needs to run migrations again.. To check if the API is working on your environment, can you access the `localhost:3000` and feedback if the Ruby on Rails index page are showing?

screen shot 2017-03-15 at 2 46 34 pm

**Review by igr-santos — APPROVED** [review]

**Comment by gabrielrtakeda** [comment]
Thanks @igr-santos! (:

**Pull request merged**
